service: modurank

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-2
  profile: modurank
  logRetentionInDays: 14
  architecture: arm64
  memorySize: 128
  timeout: 15
  versionFunctions: false
  stage: prod
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-northeast-2:*:*"
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource: "arn:aws:kms:*:*:*"

functions:
  init_room:
    handler: lambdas/init_room.handler
    name: init_room
    events:
      - http:
          path: rooms
          method: post
          cors: true

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: MoDuRank-API
        Description: API for modurank.junah.dev

    ApiGatewayCustomDomain:
      Type: AWS::ApiGateway::DomainName
      Properties:
        DomainName: api.modurank.junah.dev
        RegionalCertificateArn: arn:aws:acm:ap-northeast-2:529088284282:certificate/2b22fc86-4182-411b-8fea-2fd58a4ffc35
        EndpointConfiguration:
          Types:
            - REGIONAL
        SecurityPolicy: TLS_1_2

    ApiGatewayBasePathMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn:
        - ApiGatewayCustomDomain
        - ApiGatewayRestApi
      Properties:
        DomainName:
          Ref: ApiGatewayCustomDomain
        RestApiId:
          Ref: ApiGatewayRestApi
        Stage: ${self:provider.stage}

package:
  include:
    - "lambdas/**"
    - "shared/**"
    - "poetry.lock"
    - "pyproject.toml"
  exclude:
    - "node_modules/**"
    - "venv/**"
    - "serverless.yml"
    - ".serverless/**"
    - ".ruff_cache/**"

custom:
  pythonRequirements:
    usePoetry: true
    requirePoetryLockFile: false
    useStaticCache: false
    useDownloadCache: false
    pipCmdExtraArgs:
      - "--platform manylinux2014_aarch64"
      - "--implementation cp"
      - "--python-version 3.10"
      - "--only-binary=:all:"
      - "--upgrade"

plugins:
  - serverless-python-requirements
